### ISSUE TITLE
feat: 스터디 생성화면 Step 구현

### ISSUE THREAD

**Issue by Young-mason** [mash-up-kr/moit-web#26]
## SUMMARY

스터디 생성화면 Step 구현

## CHECKLIST

- [ ] 버튼 컴포넌트 구현
- [ ] ProgressBar 구현
- [ ] step에 따른 화면전환 구현

## ETC

이 외 특이사항을 명시해주세요.

**Comment by minsoo-web** [comment]
Step에 따른 화면전환 적용을 하실 때 @toss/slash 에서 제공하는 퍼널 컴포넌트를 활용해보는 건 어떨까요?

references

https://slash.page/ko/libraries/react/use-funnel/readme.i18n/

https://www.youtube.com/watch?v=NwLWX2RNVcw

**Comment by Young-mason** [comment]
> Step에 따른 화면전환 적용을 하실 때 @toss/slash 에서 제공하는 퍼널 컴포넌트를 활용해보는 건 어떨까요?
> 
> references
> 
> https://slash.page/ko/libraries/react/use-funnel/readme.i18n/
> 
> https://www.youtube.com/watch?v=NwLWX2RNVcw

영상 많은 도움이되네요 
본 프로젝트 에서는 Step에 따른 구현 부분이 재사용되진 않을듯해서,  
Funnel 컴포넌트를 가져다 쓰는거보단 단순화한 구조로 만들어서 사용해볼만할 것 같아요
아이디어 주셔서 감사합니다!
